---

  features:
  - { feature: bgp }
  - { feature: ospf }
  - { feature: "nv overlay" }
  - { feature: pim }

  l3_interfaces:
  - { interface: Ethernet1/1 }
  - { interface: Ethernet1/2 }

  ospf_process_id: Underlay

  ospf_area: 0
  
  asn: 65001

  address_families:
  - { afi: l2vpn, safi: evpn }
  
  bgp_neighbors:
  - { remote_as: 65001, neighbor: 1.1.1.1, update_source: Loopback0 }
  - { remote_as: 65001, neighbor: 2.2.2.2, update_source: Loopback0 }

  s1_loopback: 3.3.3.3 

  s2_loopback: 4.4.4.4 

  rp_address: 100.2.1.1
