---

  features:
  - { feature: bgp }
  - { feature: ospf }
  - { feature: interface-vlan}
  - { feature: nv overlay }
  - { feature: vnseg_vlan }

  default_vrf_interfaces:
  - { interface: Ethernet1/1 }
  - { interface: Ethernet1/2 }
  - { interface: Loopback0 }

  asn: '65001'

  ospfproc: '1'
  ospfarea: '0'

  address_families:
  - { afi: ipv4, safi: unicast }
  - { afi: l2vpn, safi: evpn }
  
  bgp_neighbors:
  - { remote_as: 65001, neighbor: 1.1.1.1, update_source: Loopback0 }
  - { remote_as: 65001, neighbor: 2.2.2.2, update_source: Loopback0 }

  ipv4_unicast_neighbor:
   - { remote_as: 65001, neighbor: 10.0.10.1 }

