---

  features:
  - { feature: bgp }
  - { feature: ospf }
  - { feature: "nv overlay" }
  - { feature: pim }
  - { feature: interface-vlan }
  - { feature: vn-segment-vlan-based }

  l3_interfaces:
  - { interface: Ethernet1/1 }
  - { interface: Ethernet1/2 }

  l2_interfaces:
  - { interface: Ethernet1/7 }
 
  ospf_process_id: Underlay

  ospf_area: 0
  
  asn: 65001

  address_families:
  - { afi: l2vpn, safi: evpn }
  - { afi: ipv4, safi: unicast }
  
  bgp_neighbors:
  - { remote_as: 65001, neighbor: 3.3.3.3, update_source: Loopback0 }
  - { remote_as: 65001, neighbor: 4.4.4.4, update_source: Loopback0 }

  rp_address: 100.2.1.1

  vlans_l2vni:
  - { vlan_id: 10, vni_id: 10010, addr: 10.0.10.1/24, mcast_grp: 239.0.0.11, vrf: Tenant-1 }

  vlans_l3vni:
  - { vlan_id: 1000, vni_id: 10000, vrf: Tenant-1 }

  vrfs:
  - { vrf: Tenant-1, vni_id: 10000, afi: ipv4, safi: unicast }

